#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum EventType.

.DESCRIPTION

Event type
#>

enum EventType {
    # enum value: "launcherOffline"
    launcherOffline
    # enum value: "connectionInitializationTimeout"
    connectionInitializationTimeout
    # enum value: "loginFailure"
    loginFailure
    # enum value: "sessionFailure"
    sessionFailure
    # enum value: "applicationFailure"
    applicationFailure
    # enum value: "launcherCapacityExceeded"
    launcherCapacityExceeded
    # enum value: "accountCapacityExceeded"
    accountCapacityExceeded
    # enum value: "applicationThresholdExceeded"
    applicationThresholdExceeded
    # enum value: "emailFailure"
    emailFailure
    # enum value: "sessionDiscoveryError"
    sessionDiscoveryError
    # enum value: "scriptEvent"
    scriptEvent
    # enum value: "latencyThresholdExceeded"
    latencyThresholdExceeded
    # enum value: "loginTimeThresholdExceeded"
    loginTimeThresholdExceeded
    # enum value: "latencyMeasurementFailed"
    latencyMeasurementFailed
    # enum value: "loginTimeMeasurementFailed"
    loginTimeMeasurementFailed
    # enum value: "emailRequest"
    emailRequest
    # enum value: "accountDisabled"
    accountDisabled
    # enum value: "sessionRequestEndedBeforeEngineBecameOnline"
    sessionRequestEndedBeforeEngineBecameOnline
    # enum value: "licenseSessionLimit"
    licenseSessionLimit
    # enum value: "testRunStarted"
    testRunStarted
    # enum value: "testRunCancelled"
    testRunCancelled
    # enum value: "testRunFailed"
    testRunFailed
    # enum value: "testRunFinished"
    testRunFinished
    # enum value: "appExecutionAbandoned"
    appExecutionAbandoned
    # enum value: "enginePaused"
    enginePaused
    # enum value: "engineResumed"
    engineResumed
    # enum value: "remoteSessionDisconnected"
    remoteSessionDisconnected
    # enum value: "scriptScreenshot"
    scriptScreenshot
    # enum value: "screenshotFailure"
    screenshotFailure
    # enum value: "dataRetentionStarted"
    dataRetentionStarted
    # enum value: "dataRetentionFinished"
    dataRetentionFinished
    # enum value: "dataRetentionFailed"
    dataRetentionFailed
    # enum value: "databaseFailure"
    databaseFailure
    # enum value: "euxInitializationFailure"
    euxInitializationFailure
    # enum value: "euxExecutionFailure"
    euxExecutionFailure
}

