#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 6.0-preview
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AccountApi' {
    Context 'Invoke-ConfigurationCreateAccount' {
        It 'Test Invoke-ConfigurationCreateAccount' {
            #$TestResult = Invoke-ConfigurationCreateAccount -AccountCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationCreateAccounts' {
        It 'Test Invoke-ConfigurationCreateAccounts' {
            #$TestResult = Invoke-ConfigurationCreateAccounts -AccountBulkCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteAccount' {
        It 'Test Invoke-ConfigurationDeleteAccount' {
            #$TestResult = Invoke-ConfigurationDeleteAccount -AccountId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteAccounts' {
        It 'Test Invoke-ConfigurationDeleteAccounts' {
            #$TestResult = Invoke-ConfigurationDeleteAccounts -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetAccount' {
        It 'Test Invoke-ConfigurationGetAccount' {
            #$TestResult = Invoke-ConfigurationGetAccount -AccountId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetAccounts' {
        It 'Test Invoke-ConfigurationGetAccounts' {
            #$TestResult = Invoke-ConfigurationGetAccounts -OrderBy "TEST_VALUE" -Direction "TEST_VALUE" -Count "TEST_VALUE" -Offset "TEST_VALUE" -IncludeTotalCount "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateAccount' {
        It 'Test Invoke-ConfigurationUpdateAccount' {
            #$TestResult = Invoke-ConfigurationUpdateAccount -AccountId "TEST_VALUE" -AccountUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateAccountEnabled' {
        It 'Test Invoke-ConfigurationUpdateAccountEnabled' {
            #$TestResult = Invoke-ConfigurationUpdateAccountEnabled -AccountId "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
