#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 6.0-preview
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'LocationApi' {
    Context 'Invoke-ConfigurationCreateLocation' {
        It 'Test Invoke-ConfigurationCreateLocation' {
            #$TestResult = Invoke-ConfigurationCreateLocation -LocationCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteLocation' {
        It 'Test Invoke-ConfigurationDeleteLocation' {
            #$TestResult = Invoke-ConfigurationDeleteLocation -LocationId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteLocations' {
        It 'Test Invoke-ConfigurationDeleteLocations' {
            #$TestResult = Invoke-ConfigurationDeleteLocations -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetLocation' {
        It 'Test Invoke-ConfigurationGetLocation' {
            #$TestResult = Invoke-ConfigurationGetLocation -LocationId "TEST_VALUE" -Include "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetLocations' {
        It 'Test Invoke-ConfigurationGetLocations' {
            #$TestResult = Invoke-ConfigurationGetLocations -OrderBy "TEST_VALUE" -Direction "TEST_VALUE" -Count "TEST_VALUE" -Offset "TEST_VALUE" -IncludeTotalCount "TEST_VALUE" -Filter "TEST_VALUE" -Include "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateLocation' {
        It 'Test Invoke-ConfigurationUpdateLocation' {
            #$TestResult = Invoke-ConfigurationUpdateLocation -LocationId "TEST_VALUE" -LocationUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
