#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 6.0-preview
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ReportConfigurationApi' {
    Context 'Invoke-ConfigurationCreateReportConfiguration' {
        It 'Test Invoke-ConfigurationCreateReportConfiguration' {
            #$TestResult = Invoke-ConfigurationCreateReportConfiguration -TestId "TEST_VALUE" -ReportConfigurationCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationCreateReportConfigurationThreshold' {
        It 'Test Invoke-ConfigurationCreateReportConfigurationThreshold' {
            #$TestResult = Invoke-ConfigurationCreateReportConfigurationThreshold -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -AppThresholdCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteReportConfiguration' {
        It 'Test Invoke-ConfigurationDeleteReportConfiguration' {
            #$TestResult = Invoke-ConfigurationDeleteReportConfiguration -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteReportConfigurationLogo' {
        It 'Test Invoke-ConfigurationDeleteReportConfigurationLogo' {
            #$TestResult = Invoke-ConfigurationDeleteReportConfigurationLogo -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteReportConfigurationThreshold' {
        It 'Test Invoke-ConfigurationDeleteReportConfigurationThreshold' {
            #$TestResult = Invoke-ConfigurationDeleteReportConfigurationThreshold -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -ThresholdId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteReportConfigurationThresholds' {
        It 'Test Invoke-ConfigurationDeleteReportConfigurationThresholds' {
            #$TestResult = Invoke-ConfigurationDeleteReportConfigurationThresholds -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteReportConfigurations' {
        It 'Test Invoke-ConfigurationDeleteReportConfigurations' {
            #$TestResult = Invoke-ConfigurationDeleteReportConfigurations -TestId "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetReportConfiguration' {
        It 'Test Invoke-ConfigurationGetReportConfiguration' {
            #$TestResult = Invoke-ConfigurationGetReportConfiguration -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -Include "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetReportConfigurationLogo' {
        It 'Test Invoke-ConfigurationGetReportConfigurationLogo' {
            #$TestResult = Invoke-ConfigurationGetReportConfigurationLogo -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetReportConfigurations' {
        It 'Test Invoke-ConfigurationGetReportConfigurations' {
            #$TestResult = Invoke-ConfigurationGetReportConfigurations -TestId "TEST_VALUE" -OrderBy "TEST_VALUE" -Direction "TEST_VALUE" -Count "TEST_VALUE" -Offset "TEST_VALUE" -IncludeTotalCount "TEST_VALUE" -Include "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationReplaceReportConfigurationThresholds' {
        It 'Test Invoke-ConfigurationReplaceReportConfigurationThresholds' {
            #$TestResult = Invoke-ConfigurationReplaceReportConfigurationThresholds -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -AppThresholdCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationRequestReport' {
        It 'Test Invoke-ConfigurationRequestReport' {
            #$TestResult = Invoke-ConfigurationRequestReport -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -ReportRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateReportConfiguration' {
        It 'Test Invoke-ConfigurationUpdateReportConfiguration' {
            #$TestResult = Invoke-ConfigurationUpdateReportConfiguration -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -ReportConfigurationUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateReportConfigurationLogo' {
        It 'Test Invoke-ConfigurationUpdateReportConfigurationLogo' {
            #$TestResult = Invoke-ConfigurationUpdateReportConfigurationLogo -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateReportConfigurationThreshold' {
        It 'Test Invoke-ConfigurationUpdateReportConfigurationThreshold' {
            #$TestResult = Invoke-ConfigurationUpdateReportConfigurationThreshold -TestId "TEST_VALUE" -ConfigurationId "TEST_VALUE" -ThresholdId "TEST_VALUE" -ThresholdUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
