#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ConfigurationGetTest200Response' {
    Context 'ConfigurationGetTest200Response' {
        It 'Initialize-ConfigurationGetTest200Response' {
            # a simple test to create an object
            #$NewObject = Initialize-ConfigurationGetTest200Response -Type "TEST_VALUE" -IsEmailEnabled "TEST_VALUE" -EmailRecipient "TEST_VALUE" -IncludeSuccessfulApplications "TEST_VALUE" -State "TEST_VALUE" -Thresholds "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -Created "TEST_VALUE" -Environment "TEST_VALUE" -Workload "TEST_VALUE" -NumberOfSessions "TEST_VALUE" -RampUpDurationInMinutes "TEST_VALUE" -TestDurationInMinutes "TEST_VALUE" -RampDownDurationInMinutes "TEST_VALUE" -ScheduleType "TEST_VALUE" -ScheduleIntervalInMinutes "TEST_VALUE" -EnableCustomScreenshots "TEST_VALUE" -RepeatCount "TEST_VALUE" -IsRepeatEnabled "TEST_VALUE" -IsEnabled "TEST_VALUE" -RestartOnComplete "TEST_VALUE" -AlertConfigurations "TEST_VALUE"
            #$NewObject | Should -BeOfType ConfigurationGetTest200Response
            #$NewObject.property | Should -Be 0
        }
    }
}
