#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DataGetTestRun200Response' {
    Context 'DataGetTestRun200Response' {
        It 'Initialize-DataGetTestRun200Response' {
            # a simple test to create an object
            #$NewObject = Initialize-DataGetTestRun200Response -Type "TEST_VALUE" -State "TEST_VALUE" -Result "TEST_VALUE" -AppFailureResults "TEST_VALUE" -AppPerformanceResults "TEST_VALUE" -Properties "TEST_VALUE" -Comment "TEST_VALUE" -Id "TEST_VALUE" -TestId "TEST_VALUE" -Created "TEST_VALUE" -Started "TEST_VALUE" -Finished "TEST_VALUE" -Counter "TEST_VALUE" -RampUpCompleted "TEST_VALUE" -ActiveSessionCount "TEST_VALUE" -StatisticsReady "TEST_VALUE" -ProductVersion "TEST_VALUE" -LoginCounts "TEST_VALUE" -EngineCounts "TEST_VALUE" -AppExecutionCounts "TEST_VALUE"
            #$NewObject | Should -BeOfType DataGetTestRun200Response
            #$NewObject.property | Should -Be 0
        }
    }
}
