#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ApplicationGroupApi' {
    Context 'Invoke-ConfigurationAddStepsToApplicationGroup' {
        It 'Test Invoke-ConfigurationAddStepsToApplicationGroup' {
            #$TestResult = Invoke-ConfigurationAddStepsToApplicationGroup -GroupId "TEST_VALUE" -ConfigurationReplaceApplicationGroupStepsRequestInner "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationCreateApplicationGroup' {
        It 'Test Invoke-ConfigurationCreateApplicationGroup' {
            #$TestResult = Invoke-ConfigurationCreateApplicationGroup -ApplicationGroupCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteApplicationGroup' {
        It 'Test Invoke-ConfigurationDeleteApplicationGroup' {
            #$TestResult = Invoke-ConfigurationDeleteApplicationGroup -GroupId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteApplicationGroupList' {
        It 'Test Invoke-ConfigurationDeleteApplicationGroupList' {
            #$TestResult = Invoke-ConfigurationDeleteApplicationGroupList -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetApplicationGroup' {
        It 'Test Invoke-ConfigurationGetApplicationGroup' {
            #$TestResult = Invoke-ConfigurationGetApplicationGroup -GroupId "TEST_VALUE" -Include "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetApplicationGroups' {
        It 'Test Invoke-ConfigurationGetApplicationGroups' {
            #$TestResult = Invoke-ConfigurationGetApplicationGroups -OrderBy "TEST_VALUE" -Direction "TEST_VALUE" -Count "TEST_VALUE" -Filter "TEST_VALUE" -Offset "TEST_VALUE" -IncludeTotalCount "TEST_VALUE" -Include "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationRemoveStepsFromApplicationGroup' {
        It 'Test Invoke-ConfigurationRemoveStepsFromApplicationGroup' {
            #$TestResult = Invoke-ConfigurationRemoveStepsFromApplicationGroup -GroupId "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationReplaceApplicationGroupSteps' {
        It 'Test Invoke-ConfigurationReplaceApplicationGroupSteps' {
            #$TestResult = Invoke-ConfigurationReplaceApplicationGroupSteps -GroupId "TEST_VALUE" -ConfigurationReplaceApplicationGroupStepsRequestInner "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateApplicationGroup' {
        It 'Test Invoke-ConfigurationUpdateApplicationGroup' {
            #$TestResult = Invoke-ConfigurationUpdateApplicationGroup -GroupId "TEST_VALUE" -ApplicationGroupUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateStepInApplicationGroup' {
        It 'Test Invoke-ConfigurationUpdateStepInApplicationGroup' {
            #$TestResult = Invoke-ConfigurationUpdateStepInApplicationGroup -GroupId "TEST_VALUE" -StepId "TEST_VALUE" -ConfigurationUpdateStepInApplicationGroupRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
