#
# Login Enterprise
# v6.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6-preview), [Documentation (ReDoc)](/publicApi/v6-preview/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <b>Public API version 5 is the preferred API to be used. Version 3 was deprecated in 4.5 and officially removed in 4.9.</b> <b>Public API version 6 is currently a preview API and is subject of (breaking) changes in the future.</b>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WorkloadApi' {
    Context 'Invoke-ConfigurationCreateTestWorkloadSteps' {
        It 'Test Invoke-ConfigurationCreateTestWorkloadSteps' {
            #$TestResult = Invoke-ConfigurationCreateTestWorkloadSteps -TestId "TEST_VALUE" -ConfigurationReplaceApplicationGroupStepsRequestInner "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteTestWorkloadStep' {
        It 'Test Invoke-ConfigurationDeleteTestWorkloadStep' {
            #$TestResult = Invoke-ConfigurationDeleteTestWorkloadStep -TestId "TEST_VALUE" -StepId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationDeleteTestWorkloadSteps' {
        It 'Test Invoke-ConfigurationDeleteTestWorkloadSteps' {
            #$TestResult = Invoke-ConfigurationDeleteTestWorkloadSteps -TestId "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetTestWorkload' {
        It 'Test Invoke-ConfigurationGetTestWorkload' {
            #$TestResult = Invoke-ConfigurationGetTestWorkload -TestId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationReplaceTestWorkloadSteps' {
        It 'Test Invoke-ConfigurationReplaceTestWorkloadSteps' {
            #$TestResult = Invoke-ConfigurationReplaceTestWorkloadSteps -TestId "TEST_VALUE" -ConfigurationReplaceApplicationGroupStepsRequestInner "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateTestWorkloadStep' {
        It 'Test Invoke-ConfigurationUpdateTestWorkloadStep' {
            #$TestResult = Invoke-ConfigurationUpdateTestWorkloadStep -TestId "TEST_VALUE" -StepId "TEST_VALUE" -ConfigurationUpdateTestWorkloadStepRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
